---
title: Wirtschaftsmathematik
author: Prof. Dr. Stefan Böcker, FRM
date: \today
toc: true
output: fhswf::presentation
knit: fhswf::render_presentation
german: true # German Dummy Text
lang: de-de   # Text Language: en-gb, en-us, de-de
---

```{r setup, include=FALSE}
options(digits = 4)
knitr::opts_chunk$set(echo=TRUE, message=FALSE, warning=FALSE, cache=FALSE, 
                      dev.args=list(pointsize=11), size="scriptsize")
```

# Organisatorisches

## Vorstellung und Kontaktdetails

### Prof. Dr. Stefan Böcker

-   Professur für Wirtschaftsinformatik, Datenbanken und mobile Technologien
-   aktuell Studiendekan und Prüfungsausschussvorsitzender des Fachbereichs Technische Betriebswirtschaft
-   Vorlesung
-   **Email:** [boecker.stefan\@fh-swf.de](mailto:boecker.stefan@fh-swf.de){.email}

### Dipl.-Math. Silke Beckmann

-   Übungen zur Vorlesung Wirtschaftsmathematik
-   **Email:** [beckmann.silke\@fh-swf.de](mailto:beckmann.silke@fh-swf.de){.email}

## Formalia

### Klausur

-   deckt den Stoff des Semesters ab
-   Dauer: 90 Minuten (Regelfall)
-   Erlaubte Hilfsmittel: **Nicht-**Programmierbarer Taschenrechner

## Unterlagen / Voraussetzungen

### Unterlagen und Informationen zum Modul Wirtschaftsmathematik

-   Es gibt einen Moodle-Kurs zum Modul [Wirtschaftsmathematik WiSe25/26](https://elearning.fh-swf.de/course/view.php?id=26721)
- **Wichtig:** Es gibt auch einen Kurs zu Terminen und Links mit allgemeinen Informationen:
[Informationen und Mitteilungen Fachbereich TBW (Präsenzstudium)](https://elearning.fh-swf.de/course/view.php?id=20812)

# Einführung in die Finanzmathematik

## Leitgedanken der Finanzmathematik

1.  Der Wert einer Zahlung ist **abhängig vom Zeitpunkt**, zu dem diese zu leisten ist.
2.  Es gilt stets das **Äquivalenzprinzip**.
3.  Das Gerüst der klassischen Finanzmathematik wird aus **ganz wenigen Formeln** gebildet.
4.  In der klassischen Finanzmathematik gibt es einfache, mittelschwere und relativ kompliziert zu lösende Probleme. Die größte Schwierigkeit ist in der Regel die **Modellierung**.
5.  Ein **grafisches Schema** bringt fast immer Klarheit.
6.  Das wichtigste Konzept ist das der **Rendite**, auch **Effektiv- oder Realzins** genannt.
7.  Die klassische Finanzmathematik läßt sich klar umreißen. Das wichtigste Konzept ist das des **Zinssatzes**.

## Begriffe

Kapital

:   Geldbetrag, der angelegt bzw. jemand anderem überlassen wird.

Laufzeit

:   Dauer der Überlassung/Anlage

Zinsen

:   Vergütung für die Kapitalüberlassung innerhalb einer Zinsperiode

Zinsperiode

:   er vereinbarten Verzinsung zugrunde liegender Zeitrahmen; meist ein Jahr, oftmals kürzer (Monat, Quartal, Halbjahr), selten länger

Zinssatz

:   insbetrag in Geldeinheiten (GE), der für ein Kapital von 100 GE in einer Zinsperiode zu zahlen ist; auch **Zinsfuß** genannt.

Zeitwert

:   der von der Zeit abhängige Wert des Kapitals

## Notation

Folgende Notation wird (in der Regel) im folgenden benutzt:

Kapital

:   $K_{t}$ ist das Kapital zum Zeitpunkt $t$

Zinssatz

:   $i = \frac{P}{100}$, wobei $p$ der Zinssatz/Zinsfuss in Prozent ist

Aufzinsungsfaktor

:   $q = \left( 1+i \right) = \left(1 + \frac{p}{100}\right)$

Zinsen

:   $Z_{t}$ Zinsen für den Zeitraum $t$.

    ```{=latex}
        \begin{center}
        Damit gelten folgende Zusammenhänge:
        \begin{tabular}{|c||c|c|c|}
                \hline \rule[-2ex]{0pt}{5.5ex}  & $p$ & $i$ & $q$ \\ 
                \hline \hline \rule[-2ex]{0pt}{5.5ex} $p$ & $p$ & $100 i$ & $100(q-1)$ \\ 
                \hline \rule[-2ex]{0pt}{5.5ex} $i$ & $\frac{p}{100}$ & $i$ & $q-1$ \\ 
                \hline \rule[-2ex]{0pt}{5.5ex} $q$ & $1+\frac{p}{100}$ & $1+i$ & $q$ \\ 
                \hline 
            \end{tabular}
        \end{center}
    ```

## Lineare Verzinsung

Zinsformel

:   Zinsen hängen proportional vom Kapital $K$, der Laufzeit $t$ und dem Zinssatz $i$ ab:

$$
Z_{t} = K \cdot i \cdot t
$$

Laufzeit

:   In Deutschland wird meist das Jahr zu 360 Tagen und der Monat zu 30 Zinstagen gerechnet. Daher kann man meist $t = \frac{T}{360}$ setzen, wobei $T$ die Anzahl an Tagen ist.

$$
Z_{T} = K \cdot i \cdot \frac{T}{360}
$$

## Beispiele (1/3)

Frage

:   Welche Zinsen fallen an, wenn ein Kapital von 3500 € vom 3. März bis zum 18. August eines Jahres bei einem Zinssatz von 3.25 % p.a. angelegt wird?

Antwort

:   Da $165=27+30+30+30+30+18$ Zinstage zugrunde zu legen sind, ergibt sich aus der Zinsformel

$$
Z_{165} = 3500\mbox{€} \cdot \frac{3.25}{100} \frac{165}{360} = 52.135416667 \mbox{€} \approx 52.14 \mbox{€}
$$

## Beispiele (2/3)

Frage

:   Wie hoch ist ein Kredit, für den in einem halben Jahr bei 8 % Jahreszinsen 657.44 € Zinsen zu zahlen sind?

Antwort

:   Durch Umstellen der Zinsformel ermittelt man:

$$
K=Z_{T} \frac{100}{p} \frac{360}{T} = 657.44 \mbox{ €} \cdot \frac{100}{8} \frac{360}{180} = 16 436 \mbox{ €}
$$

## Beispiele (3/3)

Frage

:   Ein Wertpapier über 5000 €, das mit einem Kupon (Nominalzins) von 6.25 % ausgestattet ist, wurde einige Zeit nach dem Emissionsdatum erworben. Es sind Stückzinsen in Höhe von 36.46 € zu zahlen. Wieviele Zinstage wurden dabei berechnet?

Antwort

:   Umstellen der Zinsformel führt auf

$$
T = \frac{Z_{T} \cdot 100 \cdot 360}{K \cdot p} = \frac{36.46 \cdot 100 \cdot 360}{5000 \cdot 6.25} = 42 \mbox{ (Tage)}
$$

## Zeitwert

Zeitwert

:   Da sich das Kapital $K_{t}$ zum Zeitpunkt $t$ aus dem Anfangskapital $K_{0}$ zuzüglich der im Zeitraum $t$ angefallenen Zinsen $Z_{t}$ ergibt, also

\$\$ K\_{t} = K\_{0} + Z\_{t}

\$\$

gilt, folgt aus der Zinsformel eine sehr wichtige Formel der Finanzmathematik, die **Endwertformel bei linearer Verzinsung**

$$
K_{t} = K_{0} + Z_{t} = K_{0} + K_{0} \cdot i \cdot t = K_{0} \left( 1 + i \cdot t \right) = K_{0} \left( 1 + \frac{p}{100} \cdot t \right)
$$ Barwert : Man kann durch Umstellen der Endwertformel auch den **Barwert** $K_{0}$ einer zukünftigen Zahlung $K_{t}$ berechnen

$$
K_{0} = \frac{K_{t}}{1+i \cdot t}
$$

## Beispiele

Frage

:   In einem halben Jahr ist eine Forderung von 8000 € fällig. Wie viel ist bei einer Sofortzahlung zu leisten, wenn mit einem kalkulatorischen Zins von i= 5 % gerechnet wird?

Antwort

:   Aus der Barwertformel ergibt sich

$$
K_{0} = \frac{8000}{1+0.05 \cdot \frac{1}{2}} \mbox{ €} = 7804.88 \mbox{ €}
$$

## Äquivalenzprinzip und Barwert

### Äquivalenzprinzip

Das **Äquivalenzprinzip** nutzt man in der Finanzmathematik meist in der Form eines **Barwert-Vergleichs**, indem die Barwerte von Zahlungen, die zu verschiedenen Zeitpunkten geleistet werden, berechnet werden.

## Beispiel: Äquivalenzprinzip und Barwert (1/2)

Aufgabe

:   Beim Verkauf einer Maschine werden dem Käufer zwei Angebote gemacht: Entweder 9000 € in 30 Tagen oder 9085 € in 90 Tagen. Welches Angebot ist günstiger, wenn jährlich mit 6 % bzw. mit 3 % verzinst wird? Bei welchem Zinssatz ergibt sich Gleichheit?

Lösung (1/2)

:   

Bei einer Verzinsung von 6 % ergeben sich folgende Barwerte:

$$
K_{0}^{30} = \frac{9000}{1+0.06 \cdot \frac{30}{360}} = 8955.22 \qquad          K_{0}^{90} = \frac{9085}{1+0.06 \cdot \frac{90}{360}} = 8950.74 $$

Das zweite Angebot ist also bei 6 % günstiger.

Bei einer Verzinsung von 3 % ergeben sich folgende Barwerte:

$$
K_{0}^{30} = \frac{9000}{1+0.03 \cdot \frac{30}{360}} = 8977.55 \qquad          K_{0}^{90} = \frac{9085}{1+0.03 \cdot \frac{90}{360}} = 9017.37 $$

Das erste Angebot ist also bei 3 % günstiger.

## Beispiel: Äquivalenzprinzip und Barwert (2/2)

Lösung (2/2)

:   Gleichheit der Angebote

Gleichwertigkeit beider Angebote bedeutet Gleichheit der Barwerte und führt so auf die Gleichung

$$
\frac{9000}{1+i \cdot \frac{30}{360}} = \frac{9085}{1+i \cdot \frac{90}{360}} \Leftrightarrow 9000 \cdot \left( 1 + i \frac{1}{4} \right) = 9085 \left( 1 + i \frac{1}{12} \right)  
$$

Daraus folgt $i = 0.0569 = 5.69 \%$

## Berechnung von Zinssatz und Laufzeit

### Zinssatz- und Laufzeitberechnung

Man kann aus der Endwertformel bei linearer Verzinsung sowohl den Zinssatz als auch die Laufzeit berechnen:

$$
i = \frac{1}{t} \left( \frac{K_{t}}{K_{0}} - 1\right) \qquad t = \frac{1}{i} \left( \frac{K_{t}}{K_{0}} - 1\right)
$$

### Beispiel

Frage

:   In welcher Zeit wächst eine Spareinlage von 1200 € bei 2.8 % jährlicher Verzinsung auf 1225.20 € an?

Antwort

:   

$$
t = \frac{1}{0.028} \left( \frac{1225.20}{1200} - 1 \right) = 0.75 = \frac{3}{4}
$$

## Mehrfache konstante Zahlungen - vorschüssig

Frage

:   Welcher Endbetrag ergibt sich am Ende eines Jahres, wenn monatlich am *Anfang* eines Monats *(vorschüssig)* ein stets gleichbleibender Betrag $r$ bei einem Zinssatz von $i$ angelegt wird?

Antwort

:   Die erste Zahlung wird 12 Monate lang verzinst, wächst also mit dem Faktor $1+i\frac{12}{12}$, die zweite nur 11 Monate, wächst also mit dem Faktor $1+i\frac{11}{12}$ usw. Alle Zahlungen gemeinsam ergeben damit die Gesamtsumme[^1]

[^1]: Darin kommt die Gaußsche Summenformel vor, vielleicht erinnern Sie sich?

\begin{align*}
R & = r \left( 1 + i \frac{12}{12} + 1 + i\frac{11}{12} + 1 + i \frac{10}{12} +\cdots + 1 + i \frac{1}{12} \right) \\
& = r \left( 12 + \frac{i}{12} \left( 12 + 11 + 10 + \cdots + 1 \right) \right) \\
& = r \left( 12 + \frac{i}{12}  \frac{13 \cdot 12}{2}\right) = r \left( 12 + 6.5 i \right)
\end{align*}


## Mehrfache konstante Zahlungen - nachschüssig

Frage

:   Welcher Endbetrag ergibt sich am Ende eines Jahres, wenn monatlich am *Ende* eines Monats *(nachschüssig)* ein stets gleichbleibender Betrag $r$ bei einem Zinssatz von $i$ angelegt wird?

Antwort

:   Die erste Zahlung wird 11 Monate lang verzinst, wächst also mit dem Faktor $1+i\frac{11}{12}$, die zweite nur 10 Monate, wächst also mit dem Faktor $1+i\frac{10}{12}$ usw. Alle Zahlungen gemeinsam ergeben damit die Gesamtsumme[^2]

[^2]: Darin kommt wieder die Gaußsche Summenformel, diesmal nur mit Indexverschiebung, vor!

\begin{align*}
R & = r \left( 1 + i \frac{11}{12} + 1 + i\frac{10}{12} + 1 + i \frac{9}{12} +\cdots + 1 + i \frac{0}{12} \right) \\
& = r \left( 12 + \frac{i}{12} \left( 11 + 10 + \cdots + 0 \right) \right) \\
& = r \left( 12 + \frac{i}{12}  \frac{12 \cdot 11}{2}\right) = r \left( 12 + 5.5 i \right)
\end{align*}

## Mehrfache konstante Zahlungen - beliebige Zahlungsfrequenz - Jahresersatzrate

Wird allgemein ein Jahr in $m$ kürzere Perioden der Länge $\frac{1}{m}$ aufgeteilt und zu jedem Zeitpunkt $\frac{k}{m}$ mit $k=0, 1, \ldots, m-1$, also vorschüssig eine Zahlung $r$ geleistet, so ergibt sich am Ende des Jahres ein Betrag von
$$
R^{\text{vor}} = r \left( \sum_{k=0}^{m-1} 1 + i \cdot \frac{k+1}{m} \right) = r \left( \sum_{k=1}^{m} 1 + i \cdot \frac{k}{m} \right) = r \left( m + \frac{m+1}{2} \underset{=i}{\underbrace{\frac{p}{100}}} \right)
$$

Werden die Zahlungen zu den Zeitpunkten $\frac{k}{m}$ mit $k=1, 2, \ldots, m$, also nachschüssig geleistet, so gilt
$$
R^{\text{nach}} = r \left( \sum_{k=0}^{m-1} 1 + i \cdot \frac{k}{m} \right) = r \left( m + \frac{m-1}{2} \underset{=i}{\underbrace{\frac{p}{100}}} \right)
$$

Die Beträge $R^{^\text{vor}}$ und $R^{^\text{nach}}$ heißen \textbf{vorschüssige} bzw. \textbf{nachschüssige Jahresersatzrate}. Sie geben den Wert einer jährlichen Zahlung an, die den m vor- bzw. nachschüssigen $\frac{1}{m}$-periodischen Zahlungen r äquivalent ist.

## Jahresersatzrate - Beispiel

Frage

: Ein Student schließt einen Sparplan über die Laufzeit von einem Jahr mit folgenden Konditionen ab: Einzahlungen von 75 € jeweils zu Monatsbeginn (Monatsende), Verzinsung mit 4 \% p.a., Bonus am Jahresende in Höhe von 1 \% aller Einzahlungen. Über welche Summe kann der Student am Ende des Jahres verfügen? 

Antwort

: In der Formel für die Jahresersatzrate ist hier $m=12$ und damit für den Endwert $E$ der Zahlungen ohne Bonus

\begin{align*}
E^{\text{vor}} &  = 75 \cdot \left( 12+6.5 \cdot 0.04 \right) = 919.50 \text{ bei vorschüssiger Zahlung am Monatsanfang} \\
E^{\text{nach}} &  = 75 \cdot \left( 12+5.5 \cdot 0.04 \right) = 916.50 \text{ bei nachschüssiger Zahlung am Monatsende}
\end{align*}

Die Bonuszahlung beträgt $12 \cdot 75 \cdot 0.01 = 9.00$, woraus sich die Gesamtbeträge

\begin{align*}
E^{\text{vor}}_{\text{gesamt}} & = 919.50 + 9.00 = 928.50 \text{ bei vorschüssiger Zahlung am Monatsanfang} \\
E^{\text{nach}}_{\text{gesamt}} & = 916.50 + 9.00 = 925.50 \text{ bei nachschüssiger Zahlung am Monatsende}
\end{align*}

## Skonto(abzug)

Bei sofortiger Bezahlung von Waren bzw. Dienstleistungen vor dem Fälligkeitstermin der Rechnung wird oft ein Nachlass (\textbf{Skonto}) gewährt. Bezeichnet $s$ die Größe des Skontos, $R$ den Rechnungsbetrag und $T$ die Differenztage der Zahlungsziele, so zahlt man also bei Sofortbezahlung nur den Betrag

$$
\left(1-s\right) R
$$

Den zugehörigen \textbf{Effektivzinssatz} $i_{\text{eff}}$ kann man dann mit Hilfe der Barwertformel berechnen

$$
\left(1-s\right) R = \frac{R}{1+i_{\text{eff}}\cdot\frac{T}{360}} \qquad \Leftrightarrow \qquad i = \frac{s}{1-s} \cdot \frac{360}{T}
$$

## Skonto(abzug) - Beispiel

Auf einer Handwerkerrechnung über die Summe $R$ lauten die Zahlungsbedingungen:
*Bei Zahlung innerhalb von 10 Tagen gewähren wir 2 \% Skonto. Zahlung innerhalb von 30 Tagen ohne Abzug.*
	 
Für den Effektivzins ergibt sich hier:
$$
i_{\text{eff}} = \frac{0.02}{0.98} \cdot \frac{360}{20} = 0,3673469388
$$

Man sollte also von der Möglichkeit des Skontos Gebrauch machen, da dies einer Verzinsung des Kapitals mit 36.73 \% entspricht.

## Ratenzahlungen

Oft besteht die Möglichkeit, Zahlungen entweder direkt oder als Ratenzahlungen mit gewissen Aufschlägen zu leisten.

Beispielsweise können Autoversicherungen entweder am Jahresanfang oder in zwei Raten mit jeweils 5 \% Aufschlag zum Jahresbeginn und nach einem halben Jahr gezahlt werden.

Für den Effektivzins gilt dann nach dem Äquivalenzprinzip:
$$
R =  \frac{1.05 \cdot R}{2} +  \frac{1.05 \cdot R}{2} \frac{1}{1+\frac{i}{2}}
$$

Nach Kürzen von $R$ und Auflösen nach dem Zinssatz $i$ ergibt sich ein Wert von $i=0.210526$, also 21.0526 \%. Da dieser Zinssatz relativ hoch ist, sollte man sich für die Bezahlung am Jahresanfang entscheiden.

## Zinseszinsrechnung

Wird ein Kapital über mehrere Zinsperioden (Jahre) hinweg angelegt und werden dabei jeweils am Jahresende fälligen Zinsen angesammelt und in den folgenden Jahren mitverzinst, entstehen **Zinseszinsen**.
\begin{align*}
K_{1} & = K_{0} \left( 1 + i \right) = K_{0} q \text{ mit } q= (1+i) \\
K_{2} & = K_{1} \left( 1 + i \right) = K_{1} q = K_{0} q \cdot q = K_{0} q^2 \\
K_{3} & = K_{2} \left( 1 + i \right) = K_{2} q = K_{0} q^2 \cdot q= K_{0} q^3  \\
K_{n} & = K_{0} q^n
\end{align*}

Die letztere Formel nennt sich **Endwertformel bei geometrischer Verzinsung** oder **Leibnizsche Zinseszinsformel**.

## Zinseszins - Beispiele

Für einen Sparbrief über 4000 €, der über fünf Jahre hinweg unter Zinsansammlung konstant mit 6 \% verzinst wird erhält man am Ende des 5. Jahres
$$
K_{5} = K_{0} \left(1 + 0.06 \right)^5 = 4000 \text{€} \cdot \left( 1.06 \right)^5 = 5352.60 \text{€}
$$
### Bemerkung

$K_{5}$ kann man hier auch als Endwert bezeichnen; $K_{0}$ nennt man (auch hier) Barwert (in diesem Falle der Barwert einer Zahlung in Höhe von $K_{5}$, die in fünf Jahren stattfindet). Die Formel für den Barwert ist dann:
$$
K_{0} = \frac{K_{n}}{q^{n}}
$$

## Unterjährige Verzinsung mit Zinseszins

Werden Zinsen auch unterjährig für Zinsperioden gutgeschrieben, die kleiner als ein Jahr sind, also beispielsweise nach $\frac{1}{m}$ Jahren, also $m$-mal im Jahr, so gilt analog zur Endwertformel
\begin{align*}
K_{1} & = K_{0} \left( 1 + \frac{i}{m}\right) = K_{0} q \text{ mit } q= (1+\frac{i}{m}) \\
K_{2} & = K_{1} \left( 1 + \frac{i}{m} \right) = K_{1} q = K_{0} q \cdot q = K_{0} q^2 \\
K_{3} & = K_{2} \left( 1 + i \right) = K_{2} q = K_{0} q^2 \cdot q= K_{0} q^3  \\
K_{n\cdot m} & = K_{0} q^{n \cdot m} = K_{0} \left( 1+ \frac{i}{m} \right)^{n \cdot m}
\end{align*}

Hier bezeichnet der Index $i$ am Kapital $K_{i}$ die Anzahl der Zinsperioden; da es $m$ Zinsperioden pro Jahr gibt, hat man nach $n$ Jahren $n \cdot m$ Zinsperioden verzinst. Dafür enthält der Aufzinsungsfaktor $q = \left( 1+ \frac{i}{m} \right)$ nur den $m$-ten Teil ($\frac{1}{m}$) der Zinsen p.a.

## Unterjährige Verzinsung mit Zinseszins

### Bemerkung

In der Formel für die unterjährige Verzinsung mit Zinseszins

$$
K_{n \text{ Jahre}} = K_{n \cdot m} = K_{0} \left(  1+ \frac{i}{m}\right)^{n \cdot m}
$$

könnte man die Anzahl $m$ der Zinsperioden pro Jahr beliebig groß wählen; die einzelnen Zinsperioden werden dann immer kürzer ($\frac{1}{m}$ Jahre). Betrachtet man dann den Grenzwert unendlich vieler Zinsperioden
$$
K_{n \text{ Jahre}} = \lim_{m \to \infty} K_{0} \left(  1+ \frac{i}{m}\right)^{n \cdot m} = K_{0} \lim_{m \to \infty} \left(  1+ \frac{i}{m}\right)^{n \cdot m} = K_{0} e^{i \cdot n} 
$$

so ergibt sich die Formel für \textbf{exponentielle Verzinsung}, wobei $e$ die Basis des natürlichen Logarithmus $\ln$ ist.

## Effektiver Jahrszins

Da der Endwert des Kapitals von der Anzahl der Zinsperioden (bei gleichem Zinssatz) abhängt, kann man sich fragen, was der äquivalente Zinssatz p.a. bei jährlicher Verzinsung wäre.

Dazu vergleicht man den Endwert bei jährlicher Verzinsung mit einem Zinssatz $i_{\text{eff}}$ mit dem Endwert bei m-periodischer Verzinsung mit dem Zinssatz $i$:
\begin{align*}
K_{0} \left( 1+i_{\text{eff}} \right)^{n}  & = K_{0} \left( 1+\frac{i}{m} \right)^{n \cdot m} \\
\Leftrightarrow i_{\text{eff}} & = \left( \left( 1+\frac{i}{m}  \right)^{m} -1 \right) 
\end{align*}

### Bemerkung

Der **effektive Jahreszins** (auch **Rendite** genannt) $i_{\text{eff}}$ ergibt sich als Zinssatz, mit dem das Anfangskapital $K_{0}$ nachschüssig am Jahresende verzinst werden müsste, um denselben Endbetrag zu erzielen wie bei einer unterjährig m-mal mit Zinseszins verzinsten Anlageform.

## Gemischte Verzinsung

### Bemerkung

Nur selten beginnt eine Anlage genau am Anfang einer Zinsperiode (z.B. bei jährlicher Verzinsung am Jahresanfang). Ebenso selten endet eine Anlage genau am Ende eines Zinsperiode (z.B. am Ende eines Jahres bei jährlicher Verzinsung),

In der Regel verwendet mal also eine \textbf{gemischte Verzinsung}.

### Beispiel
Welchen Endwert hat eine Anlage von 10000 € vom 15. August 2015 zu einem Zinssatz von 12 \% am 16. März 2019?

Die erste Zinsperiode ist kein ganzes Jahr, sondern nur 135 Tage. Danach kommen 3 volle Jahre, danach nochmal 76 Tage, also:
$$
K_{\text{16. März 2019}} = \left( 1+0.12\cdot\frac{135}{360}  \right) \cdot \left( 1+0.12 \right)^{3} \cdot \left( 1+0.12\frac{76}{360} \right) \approx 15053.43
$$

## Zinskurveneffekte

### Bemerkung

Nur selten sind die Zinssätze, zu denen Geld angelegt oder geliehen werden kann, unabhängig vom Anlagezeitraum. 

Eine **normale Zinskurve** zeigt vielmehr mit der Laufzeit der Anlage steigende Zinssätze.
Zudem kann das Kapital im Laufe seines Anlagezeitraums unterschiedliche Zinssätze erfahren.

### Beispiel

Ein Anfangskapital von 10000 € wird zunächst 2 Jahre lang mit 6 \% , danach 5 Jahre lang mit 7 \% und anschließend 3 Jahre lang mit 4 \% verzinst. 

\textbf{Auf welchen Endwert ist das Kapital angewachsen und welchem Effektivzins entspricht die Anlage?}
 
$$
K = K_{0} \left( 1+0.06 \right)^{2} \cdot \left( 1+0.07 \right)^{5} \cdot \left( 1+0.04 \right)^{3} 
$$

Für den Effektivzins gilt:
$$
\left(1+i_{\text{eff}}\right)^{10} = \left( 1+0.06 \right)^{2} \cdot \left( 1+0.07 \right)^{5} \cdot \left( 1+0.04 \right)^{3}
$$

## Laufzeitberechnungen

### Beispiel

In welchem Zeitraum verdreitfacht sich ein Kapital bei einem Zinssatz (mit Zinseszins) von 5 \% p.a.?

Gesucht ist die Anzahl an Jahren $n$ in der Zinseszinsformel:
$$
K_{n} = 3 \cdot K_{0} = K_{0} \cdot \left( 1+0.05 \right)^{n}
$$

Diese Gleichung hat die Lösung
$$
n = \frac{\log 3}{\log 1.05} = 22,517085304
$$

Also verdreifacht sich das Kapital bei einem Zinssatz von 5\% in etwa 22,5 Jahren.

## Zinseszinsformel

### Bemerkung

Falls man in der Zinseszinsformel mit den Aufzinsungsfaktoren rechnet, wird vieles einfacher:
\begin{align*}
K_{1} & = K_{0} \cdot (1+i) = K_{0} \cdot q \\
K_{n} & = K_{0} \cdot (1+i)^{n} = K_{0} \cdot q^{n}
\end{align*}

Das gilt auch, wenn die Zinssätze verschieden sind:
\begin{align*}
K_{1} & = K_{0} \cdot (1+i_{1}) = K_{0} \cdot q_{1} \\
K_{n} & = K_{0} \cdot (1+i_{1}) \cdot (1+i_{2}) \cdot \ldots \cdot (1+i_{n}) = K_{0} \cdot q_{1} \cdot q_{2} \cdot q_{3} \cdot \ldots \cdot q_{n}
\end{align*}

Damit gilt für den Effektivzins:
\begin{align*}
K_{n} = K_{0} \underset{=: q_{\text{eff}}}{\underbrace{(1 + i_{\text{eff}})}}^{n} & = K_{0} q_{1} q_{2} \cdots q_{n} \\
q_{\text{eff}}^{n} & = q_{1} q_{2} \cdots q_{n} \\
q_{\text{eff}} & = \sqrt[n]{q_{1} q_{2} \cdots q_{n}}
\end{align*}

Der Effektivzins ist also über das \textbf{geometrische Mittel} der Aufzinsungsfaktoren zu berechnen.

## Rentenrechnung

### Definition

Eine **Rente** bezeichnet eine regelmäßige, in gleichen Abständen fällige Zahlung.

Die einzelnen Zahlungen nennt man **Rentenraten**.

Wie bei den Zinsen sind

- bei einer **vorschüssigen Rente** die Zahlungen zu Beginn einer Periode und
- bei einer **nachschüssigen Rente** die Zahlungen am Ende einer Periode 

fällig.

## Endwert einer nachschüssigen Rente

Frage

: Welchen Wert hat eine Rente mit der nachschüssigen (N) Rentenrate $R$, die über $n$ Jahre gezahlt wird, am Ende der Laufzeit?

\begin{tabular}{|c|c|c|c|}
\hline Jahr & nachschüssige Rate & verbleibender Zeitraum & Endwert der Rate \\ 
\hline $1$ & $R$ & $n-1$ & $Rq^{n-1}$ \\ 
\hline $2$ & $R$ & $n-2$ & $Rq^{n-2}$ \\ 
\hline $3$ & $R$ & $n-3$ & $Rq^{n-3}$ \\ 
\hline \vdots & \vdots & \vdots & \vdots \\ 
\hline $n-2$ & $R$ & $2$ & $Rq^{2}$ \\ 
\hline $n-1$ & $R$ & $1$ & $Rq$ \\ 
\hline $n$ & $R$ & $0$ & $R$ \\ 
\hline 
\end{tabular}

Damit ist:
$$
R_{n}^{N} = R + Rq + Rq^{2} + R q^{3} + \ldots + Rq^{n-1} = \sum\limits_{i=1}^{n} Rq^{i-1} = R \sum\limits_{i=1}^{n} q^{i-1} = R \frac{q^{n}-1}{q-1}
$$ 

## Barwert einer nachschüssigen Rente

Frage

: Welchen Wert hat eine Rente mit der nachschüssigen (N) Rentenrate $R$, die über $n$ Jahre gezahlt wird, heute/aus heutiger Sicht?

\begin{tabular}{|c|c|c|c|}
\hline Jahr & nachschüssige Rate & verbleibender Zeitraum & Barwert der Rate \\ 
\hline $1$ & $R$ & $n-1$ & $\frac{R}{q}$ \\ 
\hline $2$ & $R$ & $n-2$ & $\frac{R}{q^{2}}$ \\ 
\hline $3$ & $R$ & $n-3$ & $\frac{R}{q^{3}}$ \\ 
\hline \vdots & \vdots & \vdots & \vdots \\ 
\hline $n-2$ & $R$ & $2$ & $\frac{R}{q^{n-2}}$ \\ \hline $n-1$ & $R$ & $1$ & $\frac{R}{q^{n-1}}$ \\ \hline $n$ & $R$ & $0$ & $\frac{R}{q^{n}}$ \\ 
\hline 
\end{tabular}

Damit ist
$$
B_{n}^{N} = \frac{R}{q} + \frac{R}{q^{2}} + \frac{R}{q^{3}} + \ldots + \frac{R}{q^{n}} = \frac{R}{q^{n}} \left( q^{n-1} + q^{n-2} + \ldots + q + 1 \right) = R \cdot \frac{1}{q^{n}} \cdot \frac{q^n-1}{q-1}
$$

## Endwert einer vorschüssigen Rente

Frage

: Welchen Wert hat eine Rente mit der vorschüssigen (V) Rentenrate $R$, die über $n$ Jahre gezahlt wird, heute/aus heutiger Sicht?

\begin{tabular}{|c|c|c|c|}
\hline Jahr & vorschüssige Rate & verbleibender Zeitraum & Endwert der Rate \\ 
\hline $1$ & $R$ & $n$ & $Rq^{n}$ \\ 
\hline $2$ & $R$ & $n-1$ & $Rq^{n-1}$ \\ 
\hline $3$ & $R$ & $n-2$ & $Rq^{n-2}$ \\ 
\hline \vdots & \vdots & \vdots & \vdots \\ 
\hline $n-2$ & $R$ & $3$ & $Rq^{3}$ \\ 
\hline $n-1$ & $R$ & $2$ & $Rq^{2}$ \\ 
\hline $n$ & $R$ & $1$ & $Rq$ \\ 
\hline 
\end{tabular}

Damit ist
$$
R_{n}^{V} = Rq + Rq^{2} + Rq^{3} + R q^{4} + \ldots + Rq^{n} = \sum\limits_{i=1}^{n} Rq^{i} = Rq \sum\limits_{i=1}^{n} q^{i-1} = Rq \frac{q^{n}-1}{q-1}
$$

## Barwert einer vorschüssigen Rente

Frage

: Welchen Wert hat eine Rente mit der vorschüssigen (V) Rentenrate $R$, die über $n$ Jahre gezahlt wird, heute/aus heutiger Sicht?

\begin{tabular}{|c|c|c|c|}
\hline Jahr & vorschüssige Rate & verbleibender Zeitraum & Barwert der Rate \\ 
\hline $1$ & $R$ & $n-1$ & $R$ \\ 
\hline $2$ & $R$ & $n-2$ & $\frac{R}{q}$ \\ 
\hline $3$ & $R$ & $n-3$ & $\frac{R}{q^{2}}$ \\ 
\hline \vdots & \vdots & \vdots & \vdots \\ 
\hline $n-2$ & $R$ & $2$ & $\frac{R}{q^{n-3}}$ \\ \hline $n-1$ & $R$ & $1$ & $\frac{R}{q^{n-2}}$ \\ \hline $n$ & $R$ & $0$ & $\frac{R}{q^{n-1}}$ \\ 
\hline 
\end{tabular}

Damit ist
\begin{align*}
B_{n}^{V} = R + \frac{R}{q} + \frac{R}{q^{2}} + \frac{R}{q^{3}} + \ldots + \frac{R}{q^{n-1}} & = \frac{R}{q^{n-1}} \left( q^{n-1} + q^{n-2} + \ldots + q + 1 \right) \\  & = R \cdot \frac{1}{q^{n}} \cdot q \frac{q^{n}-1}{q-1}
\end{align*}

## Zusammenfassung der zentralen Rentenformeln

\begin{tabular}{|c||c|c|}
\hline End-/Barwert & Rate vorschüssig & Rate nachschüssig \\ \hline
\hline Barwert& $Rq\frac{1}{q^n}\frac{q^n -1}{q-1}$ & $R\frac{1}{q^n}\frac{q^n -1}{q-1}$ \\ \hline Endwert & $Rq\frac{q^n -1}{q-1}$ & $R\frac{q^n -1}{q-1}$ \\ 
\hline 
\end{tabular}


# Funktionen

## Funktionsbegriff

## Darstellung von Funktionen

## Einige Beispiele

## Eigenschaften von reellen Funktionen

## Wichtige Funktionen

## Ableitung einer Funktion

# Lineare Gleichungssysteme

## Grundlagen zu linearen Gleichungssystemen

## Gauß-Algorithmus

## Matrizenrechnung

# Lineare Optimierung

## Problemdarstellung und grafische Lösung

## Simplex-Algorithmus

## Allgemeines lineares Optimierungsproblem

